apiVersion: gateway.k8s.aws/v1beta1
kind: TargetGroupConfiguration
metadata:
  name: frontend-tg-config
  namespace: cloudops-ecommerce-app
spec:
  targetReference:
    name: frontend
  defaultConfiguration:
    targetType: ip
