apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cartservice-secrets
  namespace: cloudops-ecommerce-app
spec:
  refreshInterval: 30m

  secretStoreRef:
    name: aws-secret-manager
    kind: ClusterSecretStore

  # El Secret nativo de K8s que ESO va a crear/mantener
  target:
    name: cartservice-secrets
    creationPolicy: Owner  # ESO es dueño del Secret, lo borra si se borra el ExternalSecret

  data:
    - secretKey: REDIS_ADDR       # Nombre de la key dentro del Secret de K8s
      remoteRef:
        key: /cloudops-ecommerce-app/dev/redis-addr