apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  refreshInterval: 30m

  secretStoreRef:
    name: aws-secret-manager
    kind: ClusterSecretStore

  target:
    name: grafana-admin-credentials
    creationPolicy: Owner
    template:
      data:
        admin-user: admin

  data:
    - secretKey: admin-password
      remoteRef:
        key: /cloudops-ecommerce-app/dev/grafana-admin-password
