nameOverride: cartservice

image:
  repository: "224039895989.dkr.ecr.us-east-1.amazonaws.com/cloudops-ecommerce-app-cartservice-ecr-repo"
  tag: "latest"

containerName: server
containerPort: 7070
portName: grpc

service:
  enabled: true
  type: ClusterIP
  port: 7070
  targetPort: 7070
  portName: grpc

resources:
  requests:
    cpu: "200m"
    memory: "64Mi"
  limits:
    cpu: "300m"
    memory: "128Mi"

env:
  - name: REDIS_ADDR
    valueFrom:
      secretKeyRef:
        name: cartservice-secrets
        key: REDIS_ADDR

terminationGracePeriodSeconds: 5

podSecurityContext:
  fsGroup: 1000
  runAsGroup: 1000
  runAsNonRoot: true
  runAsUser: 1000

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  privileged: false
  readOnlyRootFilesystem: true


livenessProbe:
  initialDelaySeconds: 15
  periodSeconds: 10
  grpc:
    port: 7070
readinessProbe:
  initialDelaySeconds: 15
  grpc:
    port: 7070

serviceAccount:
  create: true
  name: cartservice