nameOverride: loadgenerator

image:
  repository: "224039895989.dkr.ecr.us-east-1.amazonaws.com/cloudops-ecommerce-app-loadgenerator-ecr-repo"
  tag: "latest"

containerName: main
containerPort: null

service:
  enabled: false

resources:
  requests:
    cpu: "300m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

env:
  - name: FRONTEND_ADDR
    value: "frontend:80"
  - name: USERS
    value: "10"
  - name: RATE
    value: "1"

terminationGracePeriodSeconds: 5
restartPolicy: Always

podAnnotations:
  sidecar.istio.io/rewriteAppHTTPProbers: "true"

podSecurityContext:
  fsGroup: 1000
  runAsGroup: 1000
  runAsNonRoot: true
  runAsUser: 1000

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  privileged: false
  readOnlyRootFilesystem: true

initContainers:
  - name: frontend-check
    image: busybox:latest
    command:
      - /bin/sh
      - -exc
      - |
        MAX_RETRIES=12
        RETRY_INTERVAL=10
        for i in $(seq 1 $MAX_RETRIES); do
          echo "Attempt $i: Pinging frontend: ${FRONTEND_ADDR}..."
          STATUSCODE=$(wget --server-response http://${FRONTEND_ADDR} 2>&1 | awk '/^  HTTP/{print $2}')
          if [ $STATUSCODE -eq 200 ]; then
              echo "Frontend is reachable."
              exit 0
          fi
          echo "Error: Could not reach frontend - Status code: ${STATUSCODE}"
          sleep $RETRY_INTERVAL
        done
        echo "Failed to reach frontend after $MAX_RETRIES attempts."
        exit 1
    env:
      - name: FRONTEND_ADDR
        value: "frontend:80"
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      privileged: false
      readOnlyRootFilesystem: true

serviceAccount:
  create: true
  name: loadgenerator
