apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-load-balancer-controller
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: cloudops-ecommerce-app

  source:
    repoURL: https://aws.github.io/eks-charts
    chart: aws-load-balancer-controller
    targetRevision: 3.0.0

    helm:
      values: |
        clusterName: cloudops-ecommerce-app-dev
        serviceAccount:
          create: true
          annotations:
            # IRSA: permite al controller crear ALBs en tu cuenta
            eks.amazonaws.com/role-arn: "arn:aws:iam::224039895989:role/cloudops-ecommerce-app-lbc-role"
        controllerConfig:
          featureGates:
            ALBGatewayAPI: true
        region: us-east-1
        vpcId: "vpc-0f9a18dbc180170f46"

  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true