apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secrets
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: cloudops-ecommerce-app
  source:
    repoURL: https://github.com/CloudOpsDeployment/gitops
    targetRevision: main
    path: helm/enviroments/dev/secrets
  destination:
    server: https://kubernetes.default.svc
    namespace: cloudops-ecommerce-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
