# Configuración de la imagen Docker
image:
  repository: ""   # REQUERIDO: URL completa del ECR sin el tag
  tag: "latest"    # El CI lo sobreescribirá con el SHA del commit
  pullPolicy: IfNotPresent

# Flag global para habilitar/deshabilitar completamente el release
enabled: true

# Nombre del servicio — se usa en labels y nombres de recursos
nameOverride: ""

# Configuración del Service de Kubernetes
service:
  enabled: true
  type: ClusterIP   # ClusterIP para servicios internos, LoadBalancer solo para frontend
  port: 8080        # Puerto que expone el Service
  targetPort: 8080  # Puerto en el que escucha el contenedor
  portName: http

# Recursos del contenedor
# En t3.small con 1 nodo estos valores son críticos — si pides demasiado, el pod no schedula
resources:
  requests:
    cpu: "100m"      # 100 millicores = 0.1 CPU
    memory: "64Mi"
  limits:
    cpu: "200m"
    memory: "128Mi"

# Variables de entorno del contenedor
# Cada servicio sobreescribirá esto con sus propias variables
env: []
# Ejemplo de cómo se sobreescribe en values por servicio:
# env:
#   - name: PORT
#     value: "7070"
#   - name: REDIS_ADDR
#     value: "redis-cart:6379"

# Horizontal Pod Autoscaler
hpa:
  enabled: false     # Deshabilitado por default en dev (1 solo nodo)
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 70

# Número de réplicas (ignorado si hpa.enabled = true)
replicaCount: 1

# ServiceAccount — necesario para el IRSA
serviceAccount:
  create: true
  name: ""
  annotations: {}  # Aquí irá el ARN del IAM Role para IRSA

# Liveness y Readiness probes
# Cada servicio sobreescribe estos con sus endpoints reales
livenessProbe: {}
readinessProbe: {}

# Puerto que expone el contenedor (puede diferir de service.port)
containerPort: 8080
portName: http
ports: []

# Nombre del contenedor (si no se define, usa fullname)
containerName: ""

# Security context a nivel Pod
podSecurityContext: {}
podAnnotations: {}

# Controles opcionales del Pod
terminationGracePeriodSeconds: null
restartPolicy: ""
initContainers: []

# Security context a nivel contenedor
securityContext: {}

# Volúmenes y mounts opcionales
volumes: []
volumeMounts: []